### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by qamil** [gaearon/react-document-title#7] opened 2015-01-06 16:30 UTC
Since 'mountedInstances' is a static property on DocumentTitle it's shared state across all requests.
Doesn't this cause race conditions? I'm not sure I totally get how it works yet (i'm new to nodejs and react too).

**Comment by gaearon** [comment] 2015-01-06 16:39
It wouldn't be thread safe but I'm not aware of any JS environment that has threads.
Node is single-threaded too, or to be more correct, parts exposed to the user are.

That's why there are no synchronization/locking mechanisms in JS.

**Comment by gaearon** [comment] 2015-01-06 16:43
However there very well may be potential concurrency issues if parts of component hierarchy are async.
Would you like to submit a failing test?

**Comment by qamil** [comment] 2015-01-06 16:44
Yes, I'm aware of the fact that nodejs and js in general is single threaded. 
Just browsed your code a bit more, it seems like this line:
>  DocumentTitle.mountedInstances.splice(0);
in the rewind function does the magic.
Thanks anyway!

**Comment by gaearon** [comment] 2015-01-06 16:48
Yeah, it helps to clean up between the requests.
But I wonder what happens if requests are render asynchronously:

1. User A requests page, we're waiting on a promise a la [third example with `fetchData`](https://github.com/rackt/react-router/blob/master/docs/api/run.md#examples-1)
2. User B requests another page and we're waiting on another promise
3. Promise for user A completes. But whoops! The title from B's request has already leaked into static instances!

So I think there's a potential pitfall there, thanks for reporting.
I'm not sure how to solve this API-wise, what do you think?

cc @pluma

**Comment by gaearon** [comment] 2015-01-06 16:59
I wonder if we should split component in two, similar to how react-router has separate `Router.create` and `RouteHandler`.

One would be at the root, and it would be created per each request. This is where `rewind()` would be defined:

```js
var DocumentTitle = require('react-document-title');

something.serve(function (req, res) {
  // note: this runs for each request
  var DocumentTitleRoot = DocumentTitle.createRoot();

  Router.run(routes, req.path, function (Handler, state) {
    fetchData(state.matches).then(function (data) {
      var html = React.renderToString(
        <DocumentTitleRoot>
          <Handler data={data} />
        </DocumentTitleRoot>
      );

      // Get title from our per-request type
      var title = DocumentTitleRoot.rewind();

      req.send(`<html><head><title>${title}</title></head><body>${html}</body></html>`);
    });
  });
});
```

**Comment by gaearon** [comment] 2015-01-06 17:02
I think this + #5 would make a nice 1.0.

also cc @insin, I think he may have comments about this approach

**Comment by pluma** [comment] 2015-01-06 19:05
`React.renderToString` (which is used to render React on the server) is synchronous, so the entire point seems moot. The only environment in which race conditions could be an issue are multi-threaded ones using `React.render` (which requires a DOM) -- but then the DOM is already broken if it is shared between threads.

As long as you don't make assumptions about the state of the components outside the event loop iteration in which they were rendered, you'll be fine. Just fetch the current document title immediately after rendering if you need to access it asynchronously.

**Comment by gaearon** [comment] 2015-01-06 20:22
Oh wait, you're actually right.
`fetchData` example is async but `componentWillMount` and friends run sync inside `renderToString`.

Sorry, that was a brainfart on my part!
Closing.

**Closed by gaearon** 2015-01-06 20:22 UTC

**Comment by insin** [comment] 2015-01-06 21:17
FWIW, I had the *exact* same brainfart with `fetchData` and this :smile:

**Comment by gaearon** [comment] 2015-01-06 21:22
lol

**Comment by halt-hammerzeit** [comment] 2017-03-06 05:44
@gaearon 
> It wouldn't be thread safe but I'm not aware of any JS environment that has threads.
Node is single-threaded too, or to be more correct, parts exposed to the user are.
That's why there are no synchronization/locking mechanisms in JS.

Wrong.
The point of Node.js is not being single threaded — it would be absolutely pointless that way.
The point of Node.js is that it's concurrent by its very nature the main thing being streams and events.
So this library surely has a bug and breaks in case of any concurrency.

**Comment by halt-hammerzeit** [comment] 2017-03-06 06:51
@pluma 
> React.renderToString (which is used to render React on the server) is synchronous, so the entire point seems moot. 

Wrong.
There's a big movement currently towards asynchronous rendering in React and it has been admitted even in Facebook themselves.

**Comment by pluma** [comment] 2017-03-06 10:28
@halt-hammerzeit First of all, please consider adjusting your tone. "Wrong" is unnecessarily confrontational and not conducive to any discussion. If you want a maintainer of an open source project to change something in their code for you, you probably should try not to alienate them. I'm chalking this down to a language barrier thing but others might just decide to ignore you if you start them off like that.

Now to your comments:

> The point of Node.js is that it's concurrent by its very nature

The dismissal of "thread safety" was based on the original title of this issue. Node.js indeed doesn't use threads, nor do any browsers. In fact, multi-threaded JS environments (in the sense that C++ or Java are multi-threaded) would be inherently incompatible with much of the JS ecosystem, hence @gaearon's dismissal of the worries about "thread safety".

To clarify: there are environments where JS is executed on multiple threads, but the threads are almost completely isolated. For example web workers are basically worker threads but they can only communicate with the main thread via strings, not shared objects.

> There's a big movement currently towards asynchronous rendering in React

I'm sure @gaearon is aware of that as you're likely talking about Fiber. However the comment you're replying to is from January 2015, more than two years ago. At the time `renderToString` was synchronous and it's been that way for a long while. So not only wasn't my statement wrong within its context but it's still true now. The change from synchronous to asynchronous will be backwards incompatible so by definition pre-existing code may break in (un)expected ways.

That said, with renderToString potentially becoming asynchronous in the future it's probably worth looking into how to make `react-document-title` (and similar libraries like `react-helmet`) work without relying on global state. When this library came out Context wasn't a big thing yet and even state libraries generally didn't use it (Redux itself didn't get started until May 2015 and wasn't really "a thing" until July 2015 when Dan presented it at React Europe). It'd be interesting to come back to these problems with a modern understanding of React and see what could be done differently.

**Comment by halt-hammerzeit** [comment] 2017-03-06 10:29
@pluma 
> First of all, please consider adjusting your tone. "Wrong" is unnecessarily confrontational and not conducive to any discussion. If you want a maintainer of an open source project to change something in their code for you, you probably should try not to alienate them. I'm chalking this down to a language barrier thing but others might just decide to ignore you if you start them off like that.

Don't you tell me how to express my attitude, boy

**Comment by halt-hammerzeit** [comment] 2017-03-06 10:30
> The dismissal of "thread safety" was based on the original title of this issue. Node.js indeed doesn't use threads, nor do any browsers.

This has nothing to do with "threads", it is about "thread safety", so you clearly don't understand the real meaning of this phrase.

**Comment by halt-hammerzeit** [comment] 2017-03-06 10:31
> So not only wasn't my statement wrong within its context but it's still true now. 

No, it was and it is still wrong

**Comment by halt-hammerzeit** [comment] 2017-03-06 10:32
>  The change from synchronous to asynchronous will be backwards incompatible so by definition pre-existing code may break in (un)expected ways.

Yeah, if you release a broken package once, you can't ever update it, right, because it would break things that are already broken, sure, great logic in that.

**Comment by halt-hammerzeit** [comment] 2017-03-06 10:33
He's not "Dan" by the way, he is "Daniil"

**Comment by pluma** [comment] 2017-03-06 10:46
> Don't you tell me how to express my attitude, boy

You are at liberty to express yourself however you want. But everybody else is also at liberty to ignore you if you are unnecessarily hostile.

> This has nothing to do with "threads", it is about "thread safety", so you clearly don't understand the real meaning of this phrase.

Here's what Wikipedia has to say:

> Thread safety is a computer programming concept applicable in the context of multithreaded programs. A piece of code is thread-safe if it manipulates shared data structures only in a manner that guarantees safe execution by multiple threads at the same time.

Note how it says "in the context of multithreaded programs". No threads, no thread safety. The title was later corrected to put "thread safety" in scarequotes because the issue is about concurrency in general rather than thread safety in the concrete sense.

> Yeah, if you release a broken package once, you can't ever update it, right, because it would break things that are already broken, sure, great logic in that.

Within the limitations of React at the time, this library is not broken. It's still possible to use it correctly although you need to be aware that the title can only be read in the same tick `renderToString` was called. So it's not broken, just error prone when used incorrectly. But it's certainly not future proof (i.e. it will no longer be useful when the API changes post-Fiber) and it's worth revisting this and other libraries built on `react-side-effect` to address that concern.

That said, this is the last time I will respond to your comments here. I have better things to do than spending my free time on people as abrasive as you are presenting yourself here.

**Comment by halt-hammerzeit** [comment] 2017-03-06 10:48
> I have better things to do than spending my free time

You already have, a plenty, actually, all that wikipedia citation and such.
You can never reclaim it back.
Deal with it.

**Comment by catamphetamine** [comment] 2017-09-26 21:23
Reminder: React 16 is out and `ReactDOMNodeStream.renderToNodeStream(element)` is there.
