### ISSUE TITLE
set default title

### ISSUE THREAD

**Issue by guilherme90** [gaearon/react-document-title#19] opened 2015-06-18 12:08 UTC
Hello. Do you think it would be interesting to insert a form of default title for the application, and other pages where I set the DocumentTitle he "add" my title that set along with what I'm setting on the page?

**Comment by arkist** [comment] 2015-06-25 10:41
see #6

**Comment by gaearon** [comment] 2015-08-25 19:34
Duplicate of #6.

**Closed by gaearon** 2015-08-25 19:34 UTC
